apiVersion: apps/v1
kind: Deployment

metadata:
  name: permission
  namespace: emortalmc
  labels:
    app: permission

spec:
  replicas: 3
  selector:
    matchLabels:
      app: permission

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: permission
    spec:
      containers:
        - name: permission
          image: ghcr.io/emortalmc/permission-service-go:f0b454903a5e5159d8f2bd6cf9d3eb028752250a
          ports:
            - name: grpc
              containerPort: 9010

          env:
            - name: "DEVELOPMENT"
              value: "false"
            - name: KAFKA_HOST
              value: default-kafka-bootstrap
            - name: KAFKA_PORT
              value: "9092"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: permission-service-db-creds
                  key: connection-string
            - name: PORT
              value: "9010"
