apiVersion: v1
kind: Service

metadata:
  namespace: emortalmc
  name: permission

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: permission
