name: "Docker Build"

on:
  push: {}
  pull_request:
    types: [ opened, reopened ]

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup Go"
        uses: "actions/setup-go@v4"
        with:
          go-version: "1.20"
          cache: false

      - name: "Lint Go"
        uses: "golangci/golangci-lint-action@v3"
        with:
          version: "latest"
          args: "--timeout 2m0s"

  test:
    strategy:
      fail-fast: false
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup Go (cached)"
        uses: "actions/setup-go@v4"
        with:
          cache: true
          go-version-file: "go.mod"
          go-version: "1.20"

      - name: "Test"
        run: "make test"

  build:
    if: "github.event_name == 'push' && github.ref == 'refs/heads/main'"
    needs: [ lint, test ]
    runs-on: "ubuntu-latest"
    outputs:
      image: "${{ steps.build.outputs.image }}"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Login to container registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Build and push"
        uses: "docker/build-push-action@v4"
        with:
          context: "."
          file: "./Dockerfile"
          push: true
          tags: "ghcr.io/${{ github.repository }}:${{ github.sha }}"

  deploy:
    needs: "build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          ref: "deployment"

      - name: "Update deployment file"
        run: |
          sed -i 's|image: .*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g' deployment.yaml
          git add deployment.yaml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Update deployment to ${{ github.sha }}"
          git push
